########################
# Troop types
########################

# Nomads
TROOP_TYPE_VET_SABER_CLEAVER = 5
TROOP_TYPE_VET_SLINGSHOT = 6
TROOP_TYPE_VET_DEMON_HORROR = 9  # MELEE
TROOP_TYPE_VET_DEATHLY_HORROR = 10  # RANGE
TROOP_TYPE_VET_FLAME_BEARER = 11  # Super Super Melee defender
TROOP_TYPE_VET_COMPOSITE_BOWMAN = 12  # Super Super Range defender

TROOP_TYPE_MUSCLE_MAN = 13  # Berimond Melee
TROOP_TYPE_MARKSMAN = 14  # Berimond Range

TROOP_TYPE_IMPERIAL_GUARDSMAN = 18  # (melee) Can be recruited after you participate on berimond and get a title
TROOP_TYPE_IMPERIAL_BOWMAN = 19  # Can be recruited after you participate on berimond and get a title

TROOP_TYPE_BERSERKER = 22
TROOP_TYPE_SPEAR_WOMAN = 23

TROOP_TYPE_RENEGADE_SAI_WARRIOR = 34  # Samurai melee offense
TROOP_TYPE_RENEGADE_ARROW_THROWER = 35  # Samurai range offense
TROOP_TYPE_RENEGADE_KATANA_WARRIOR = 36  # Samurai melee defender
TROOP_TYPE_RENEGADE_BOW_MASTER = 37  # Samurai range defender
TROOP_TYPE_ELITE_SKELETON_WARRIOR = 40
TROOP_TYPE_ELITE_SKELETON_BOWMAN = 41

TROOP_TYPE_BONE_HUNTRESS = 48  # Winter event melee troops
TROOP_TYPE_FROST_BOWMAN  = 50 # Winter event range troops
TROOP_TYPE_MASTER_BONE_HUNTRESS = 51  # Winter event melee troops (powerful)
TROOP_TYPE_MASTER_FROST_BOWMAN = 52  # Winter event range troops (powerful)

TROOP_TYPE_ELITE_KNIGHT = 75  # KG Elite
TROOP_TYPE_ELITE_CROSSBOWMAN = 76  # KG Elite

TROOP_TYPE_FOREST_WARRIOR = 83  # (melee)

# New black VET types
TROOP_TYPE_VET_HALBERDIER = 308
TROOP_TYPE_VET_TWO_HANDED_SWORDSMAN = 309
TROOP_TYPE_VET_LONGBOWMAN = 311
TROOP_TYPE_VET_HEAVY_CROSSBOWMAN = 312

TROOP_TYPE_SWORDSMAN = 601
TROOP_TYPE_SPEARMAN = 602
TROOP_TYPE_MACEMAN = 603
TROOP_TYPE_HALBERDIER = 604
TROOP_TYPE_TWO_HANDED_SWORDSMAN = 605
TROOP_TYPE_ARCHER = 606
TROOP_TYPE_CROSSBOWMAN = 607
TROOP_TYPE_BOWMAN = 608
TROOP_TYPE_HEAVY_CROSSBOWMAN = 609
TROOP_TYPE_LONGBOWMAN = 610

TROOP_TYPE_SHADOW_MACEMAN = 612
TROOP_TYPE_SHADOW_CROSSBOWAN = 613

TROOP_TYPE_VET_SPEARMAN = 628  # Red vet
TROOP_TYPE_VET_MACEMAN = 630  # Red vet
TROOP_TYPE_VET_BOWMAN = 631  # Red vet
TROOP_TYPE_DUMMY_MELEE_SOLDIER = 632
TROOP_TYPE_DUMMY_RANGED_SOLDIER = 633
TROOP_TYPE_VET_CROSSBOWMAN = 636  # Red vet
TROOP_TYPE_DUMMY_ARCHERS = 639
TROOP_TYPE_ARMED_CITIZEN = 652
TROOP_TYPE_TRAVELING_CROSSBOWMAN = 656
TROOP_TYPE_TRAVELING_KNIGHT = 655
TROOP_TYPE_KINGSGUARD_BOW = 664
TROOP_TYPE_SHADOW_ROGUE = 667  # Shadow 2 handed swordman
TROOP_TYPE_SHADOW_FELON = 668  # Shadow crossbow

TROOP_TYPE_KINGSGUARD_KNIGHT = 672
TROOP_TYPE_PYROMANIAC = 685
TROOP_TYPE_KINGSGUARD_ROYAL_SENTINEL = 686
TROOP_TYPE_KINGSGUARD_ROYAL_SCOUT = 687

TROOP_TYPE_MARAUDER = 684  # I think


# In RBC spy reports these are the IDs given to sands natives (need to check again 688 and 689, I think the game uses 2 different IDs, one for RBC defenders and one for 'renegades' you can own)
TROOP_TYPE_SABER_WARRIOR = 675  # Desert native sword
TROOP_TYPE_DESERT_BOWMAN = 676  # Desert native bow


TROOP_TYPE_RENEGADE_SABER_WARRIOR = 688  # Desert native sword
TROOP_TYPE_RENEGADE_DESERT_BOWMAN = 689  # Desert native bow
TROOP_TYPE_RENEGADE_NORSEMAN_WARRIOR = 690  # Ice native axe
TROOP_TYPE_RENEGADE_NORSEMAN_BOWMAN = 691  # Ice native bow
TROOP_TYPE_RENEGADE_CULTIST_WARRIOR = 692  # Fire native axe
TROOP_TYPE_RENEGADE_CULTIST_BOWMAN = 693  # Fire native bow

TROOP_TYPE_DEMON_HORROR = 714  # Melee
TROOP_TYPE_DEATHLY_HORROR = 715  # Bow
TROOP_TYPE_BARBARIAN = 721
TROOP_TYPE_COMPOSITE_BOWMAN = 722  # 159 Range defense (super high level defender)
TROOP_TYPE_FLAME_BEARER = 723  # 170 Melee defense (super high level defender)
TROOP_TYPE_VET_SWORDMAN = 724
TROOP_TYPE_KHAN_GUARDS = 725  # 175 melee attack
TROOP_TYPE_SABER_CLEAVER = 726  # Low level melee nomad attacker
TROOP_TYPE_SLINGSHOT = 727  # Low level range nomad attacker
TROOP_TYPE_RENEGADE_SPEAR_THROWER = 729  # Range defender

TROOP_TYPE_LANCE = 743          # melee nomad defender found in towers
TROOP_TYPE_SPEAR_THROWER = 744  # range nomad defender found in towers

TROOP_TYPE_RENEGADE_SWASHBUCKLER = 759  # Melee Pirate, 166 melee attack power
TROOP_TYPE_RENEGADE_SAIL_RIPPER = 760  # Range Pirate, 166 melee attack power
TROOP_TYPE_VET_MARAUDER = 765
TROOP_TYPE_VET_PYROMANIAC = 766


##################################
# Armorer tool purchase tool ids
##################################
ARMORER_TOOL_PURCHASE_TYPE_LADDER = 28
ARMORER_TOOL_PURCHASE_TYPE_BATTERING_RAM = 32
ARMORER_TOOL_PURCHASE_TYPE_MANTLET = 36

ARMORER_TOOL_PURCHASE_TYPE_BELFRY = 29
ARMORER_TOOL_PURCHASE_TYPE_SHIELD_WALL = 37
ARMORER_TOOL_PURCHASE_TYPE_BOULDERS = 41
ARMORER_TOOL_PURCHASE_TYPE_HEAVY_RAM = 33

##################################
# Armorer tool cost
##################################

# Coins
ARMORER_TOOL_PURCHASE_TYPE_LADDER_PRICE = 220
ARMORER_TOOL_PURCHASE_TYPE_BATTERING_RAM_PRICE = 430
ARMORER_TOOL_PURCHASE_TYPE_MANTLET_PRICE = 810

# Rubies
ARMORER_TOOL_PURCHASE_TYPE_BELFRY_PRICE = 27  # 27 rubies (might have been on special as it was a best seller)
ARMORER_TOOL_PURCHASE_TYPE_SHIELD_WALL_PRICE = 41
ARMORER_TOOL_PURCHASE_TYPE_BOULDERS_PRICE = 46
ARMORER_TOOL_PURCHASE_TYPE_HEAVY_RAM_PRICE = 32

########################
# Tool types
########################
TOOL_TYPE_KHAN_CHEST = 1  # Nomad chest
TOOL_TYPE_SPIKED_SHIELD = 2  # FL shield tool
TOOL_TYPE_THE_WOLFS_HOWL = 3  # Melee and glory attack tool
TOOL_TYPE_TONNELON = 4  # Wall & Glory attack tool
TOOL_TYPE_THE_SPLENDOR_OF_BERIMOND = 16  # Berimond (2% gallantry flag)
TOOL_TYPE_BANNER_OF_TRIUMPH = 24  # 4% glory flag
TOOL_TYPE_GATE_STORMER = 25  # Samurai Ram
TOOL_TYPE_FOLDING_LADDER = 26  # Samurai Wall attack tool
TOOL_TYPE_SWIVELING_SHIELD = 27  # Samurai shield
TOOL_TYPE_SMOKE_BOMB = 46  # Samurai Moat tool
TOOL_TYPE_SAMURAI_BANNER = 47  # Samurai glory
TOOL_TYPE_SHIELD_SLED = 55  # Winter event shield (same as iron mantlet)
TOOL_TYPE_BANNER_OF_THE_FROST_WARRIORS = 61  # XP Banner
TOOL_TYPE_NOMAD_PIGGY_BANK = 62  # Nomad 1% coins
TOOL_TYPE_THE_WINTER_KINGS_BANNER = 64  # Winter event 3% glory banner
TOOL_TYPE_PREMIUM_PIGGY_BANK = 67  # +2% coins
TOOL_TYPE_GOLDEN_PIGGY_BANK = 73  # +5% coins
TOOL_TYPE_HEROES_BANNER = 77  # 3% glory (expensive) banners
TOOL_TYPE_SOLDIERS_BANNER = 91  # # 10% XP banner
TOOL_TYPE_BATTERING_RAM = 611
TOOL_TYPE_LADDER = 614
TOOL_TYPE_SHADOW_RAM = 615
TOOL_TYPE_SHADOW_LADDER = 616
TOOL_TYPE_WOOD_BUNDLE = 617
TOOL_TYPE_SHADOW_BUNDLES = 618
TOOL_TYPE_SHADOW_SHIELDS = 619
TOOL_TYPE_MANTLET = 620
TOOL_TYPE_PORTCULLIS = 622  # Armorer tool (Gates)
TOOL_TYPE_ARROW_SLIT = 624  # Armorer tool (Slits)
TOOL_TYPE_FIRE_MOAT = 625  # Armorer tool (Slits)
TOOL_TYPE_CASTLE_GATE_REINFORCEMENT = 626  # RSS tool
TOOL_TYPE_MURDER_HOLE = 627  # Armorer tool (Machicolations)
TOOL_TYPE_FLAMING_ARROWS = 629  # Arrows
TOOL_TYPE_SHARPENED_STAKES = 634
TOOL_TYPE_CAST_IRON_MANTLET = 635
TOOL_TYPE_HURLING_ROCKS = 637  # Cheap defensive rocks
TOOL_TYPE_SIEGE_TOWER = 640
TOOL_TYPE_IRON_RAM = 641
TOOL_TYPE_ASSAULT_BRIDGE = 642
TOOL_TYPE_INSULATING_MAT = 644  # Ruby tool
TOOL_TYPE_BULWARK = 645
TOOL_TYPE_SWAMP_SNAPPER = 646  # Ruby tool
TOOL_TYPE_TAR_PITCH_KETTLE = 647  # Ruby tool
TOOL_TYPE_HEAVY_RAM = 648  # Armorer tool
TOOL_TYPE_BELFRY = 649  # Armorer tool
TOOL_TYPE_BOULDERS = 650  # Armorer tool
TOOL_TYPE_SHIELD_WALL = 651  # Armorer tool
TOOL_TYPE_LOOT_SACK = 653
TOOL_TYPE_LOOT_CART = 654
TOOL_TYPE_BANNER = 660  # Cheap red rss glory banner
TOOL_TYPE_GLORY_BANNER = 661
TOOL_TYPE_LIME_POWDER_BOMB = 730  # Special tool/event prize
TOOL_TYPE_BODKIN_ARROWHEADS = 731  # Special tool/event prize (I think these are the blue pointed needles for defense)
TOOL_TYPE_TURTLE_RAM = 732  # Think it is given during nomads (it is a ram)
TOOL_TYPE_HORSETAIL_STANDARD = 734  # 4% glory flags
TOOL_TYPE_WAR_HORN = 737

TOOL_TYPE_INVADER_RAM = 770  # FL ram
TOOL_TYPE_INVADER_LADDER = 771  # FL ladder
TOOL_TYPE_INVADER_MASK = 773  # FL shield
TOOL_TYPE_BANNER_OF_THE_FOREIGN_INVADERS = 774  # FL Glory banner
TOOL_TYPE_THE_CLAW = 775  # Berimond gate tool
TOOL_TYPE_PAW_LADDER = 776  # Berimond ladder
TOOL_TYPE_BERIMOND_SHIELD = 778  # Berimond shield
TOOL_TYPE_THE_GLORY_OF_BERIMOND = 779  # Berimond 4% gallantry flag

################
# UNRESOLVED YET
################
TROOP_OR_TOOL_UNKNOWN_ID_615 = 615  # 75 IN ice
TROOP_OR_TOOL_UNKNOWN_ID_618 = 618  # 65 IN ice
TROOP_OR_TOOL_UNKNOWN_ID_619 = 619  # 65 IN ice
TROOP_OR_TOOL_UNKNOWN_ID_729 = 729
TROOP_OR_TOOL_UNKNOWN_ID_732 = 732  # 20 IN main

########################
# Buildings
########################
BUILDING_HOSPITAL_LEVEL_1 = 1
BUILDING_HOSPITAL_LEVEL_2 = 2
BUILDING_HOSPITAL_LEVEL_3 = 3

BUILDING_STONE_QUARRY_LEVEL_1 = 105
BUILDING_STONE_QUARRY_LEVEL_2 = 106
BUILDING_STONE_QUARRY_LEVEL_3 = 107
BUILDING_STONE_QUARRY_LEVEL_4 = 108
BUILDING_STONE_QUARRY_LEVEL_7 = 184  # Confirmed
BUILDING_STONE_QUARRY_LEVEL_9 = 186  # Confirmed
BUILDING_STONE_QUARRY_LEVEL_10 = 228  # Confirmed

BUILDING_FARMHOUSE_LEVEL_1 = 110
BUILDING_FARMHOUSE_LEVEL_2 = 111
BUILDING_FARMHOUSE_LEVEL_3 = 112
BUILDING_FARMHOUSE_LEVEL_4 = 113
BUILDING_FARMHOUSE_LEVEL_5 = 114
BUILDING_FARMHOUSE_LEVEL_6 = 187
BUILDING_FARMHOUSE_LEVEL_7 = 188
BUILDING_FARMHOUSE_LEVEL_8 = 189
BUILDING_FARMHOUSE_LEVEL_9 = 190
BUILDING_FARMHOUSE_LEVEL_10 = 195

BUILDING_WOOD_CUTTER_LEVEL_1 = 100
# BUILDING_WOOD_CUTTER_LEVEL_2 = ? speculate 101
BUILDING_WOOD_CUTTER_LEVEL_3 = 102
BUILDING_WOOD_CUTTER_LEVEL_4 = 103
BUILDING_WOOD_CUTTER_LEVEL_5 = 104
BUILDING_WOOD_CUTTER_LEVEL_6 = 179
BUILDING_WOOD_CUTTER_LEVEL_7 = 180
BUILDING_WOOD_CUTTER_LEVEL_8 = 181
BUILDING_WOOD_CUTTER_LEVEL_9 = 182
BUILDING_WOOD_CUTTER_LEVEL_10 = 227

BUILDING_DWELLING_LEVEL_1 = 127
BUILDING_DWELLING_LEVEL_2 = 128
BUILDING_DWELLING_LEVEL_3 = 129
BUILDING_DWELLING_LEVEL_5 = 131
BUILDING_DWELLING_LEVEL_6 = 191
BUILDING_DWELLING_LEVEL_10 = 198
BUILDING_TOWNHOUSE_LEVEL_11 = 230

BUILDING_SAW_MILL_LEVEL_1 = 115
BUILDING_SAW_MILL_LEVEL_2 = 116
# BUILDING_SAW_MILL_LEVEL_3 = ?

BUILDING_STONE_MASON_LEVEL_1 = 118
# BUILDING_STONE_MASON_LEVEL_2 = ?
# BUILDING_STONE_MASON_LEVEL_3 = ?


BUILDING_FLOUR_MILL_LEVEL_1 = 121
BUILDING_FLOUR_MILL_LEVEL_2 = 122
BUILDING_FLOUR_MILL_LEVEL_3 = 123
BUILDING_FLOUR_MILL_LEVEL_6 = 779

BUILDING_STORE_HOUSE_LEVEL_1 = 132
BUILDING_STORE_HOUSE_LEVEL_2 = 133
BUILDING_STORE_HOUSE_LEVEL_3 = 134

BUILDING_MARKET_PLACE_LEVEL_1 = 137
BUILDING_MARKET_PLACE_LEVEL_4 = 140  # Confirmed
BUILDING_MARKET_PLACE_LEVEL_6 = 197  # Confirmed
BUILDING_MARKET_PLACE_LEVEL_7 = 532  # Confirmed

BUILDING_BARRACKS_LEVEL_1 = 160
BUILDING_BARRACKS_LEVEL_2 = 161
BUILDING_BARRACKS_LEVEL_3 = 162
BUILDING_BARRACKS_LEVEL_4 = 163
BUILDING_BARRACKS_LEVEL_5 = 164

BUILDING_TAVERN_LEVEL_1 = 145
# BUILDING_TAVERN_LEVEL_2 = ?
BUILDING_TAVERN_LEVEL_3 = 147

# TODO was this from the bladecoast?
BUILDING_ENCAMPMENT_LEVEL_1 = 151

BUILDING_SIEGE_WORKSHOP_LEVEL_1 = 165
BUILDING_SIEGE_WORKSHOP_LEVEL_2 = 166
BUILDING_SIEGE_WORKSHOP_LEVEL_3 = 167

BUILDING_KEEP_LEVEL_1 = 171
BUILDING_KEEP_LEVEL_2 = 172
BUILDING_KEEP_LEVEL_3 = 173
BUILDING_KEEP_LEVEL_4 = 174  # Confirmed

BUILDING_BAKERY_LEVEL_4 = 196

BUILDING_ESTATE_LEVEL_1 = 148

BUILDING_GUARD_HOUSE_LEVEL_1 = 154
BUILDING_GUARD_HOUSE_LEVEL_2 = 155
BUILDING_GUARD_HOUSE_LEVEL_3 = 156

BUILDING_WATCHTOWER_LEVEL_5 = 158

BUILDING_DEFENSE_WORKSHOP_LEVEL_1 = 176
# BUILDING_DEFENSE_WORKSHOP_LEVEL_2 = ?
# BUILDING_DEFENSE_WORKSHOP_LEVEL_3 = ?

BUILDING_STABLES_LEVEL_1 = 214
BUILDING_STABLES_LEVEL_2 = 215
BUILDING_STABLES_LEVEL_3 = 226
BUILDING_LOOT_WAREHOUSE = 216  # RV related

BUILDING_STORE_HOUSE_LEVEL_7 = 232

BUILDING_DECO_SUPPLIES = 301
BUILDING_DECO_SIGNPOST = 302
BUILDING_DECO_WITCH_WELL = 304
BUILDING_DECO_MARKET_STALL = 313
BUILDING_DECO_SUNDIAL = 315
BUILDING_DECO_THEATER = 321
BUILDING_DECO_FESTIVAL_SQUARE = 323
BUILDING_DECO_CASTLE_GARDEN = 324
BUILDING_DECO_PILLORY = 331
BUILDING_DECO_COLOSSUS = 342
BUILDING_DECO_DRAGON_FOUNTAIN = 358

BUILDING_GLASS_FURNACE_LEVEL_3 = 433
BUILDING_GRANARY_LEVEL_10 = 599
BUILDING_HUNTING_LODGE_LEVEL_1 = 506

########################
# Blade coast building ids
########################
BUILDING_BLADE_COAST_SMALL_TENTS_LEVEL_1 = 263
BUILDING_BLADE_COAST_SMALL_TENTS_LEVEL_2 = 371
BUILDING_BLADE_COAST_DRILL_GROUND = 330
BUILDING_BLADE_COAST_MAIN = 259
BUILDING_BLADE_COAST_STOREHOUSE = 265

########################
# Berimond building ids
########################
BUILDING_BERIMOND_LARGE_TENTS_LEVEL_1 = 244
# BUILDING_BERIMOND_SMALL_TENTS_LEVEL_1 = ?
BUILDING_BERIMOND_SMALL_TENTS_LEVEL_2 = 11
BUILDING_BERIMOND_SMALL_TENTS_LEVEL_3 = 243
BUILDING_BERIMOND_SMALL_TENTS_LEVEL_4 = 12
BUILDING_BERIMOND_SUPPLY_STOREHOUSE_LEVEL_1 = 246
BUILDING_BERIMOND_STABLES_LEVEL_1 = 247
BUILDING_BERIMOND_MARKET_PLACE_LEVEL_1 = 249
BUILDING_BERIMOND_MAIN_TENT = 233
BUILDING_BERIMOND_ARSENAL = 336
BUILDING_BERIMOND_FIELD_KITCHEN = 337
BUILDING_BERIMOND_FIELD_HOSPITAL_LEVEL_1 = 468
BUILDING_BERIMOND_FIELD_HOSPITAL_LEVEL_2 = 20
BUILDING_BERIMOND_HEADQUARTERS_LEVEL_2 = 623
BUILDING_BERIMOND_HEADQUARTERS_LEVEL_3 = 624  # Caps off at 600 troops (but hitting a couple of towers adds a 100 troop max bonus)
# BUILDING_BERIMOND_HEADQUARTERS_LEVEL_4 = 625  # TODO need to confirm (i skipped the checks)
BUILDING_BERIMOND_HEADQUARTERS_LEVEL_5 = 626  # Caps off at 1000 troops
BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_1 = 627  # Can recruit 5 per slot
BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_2 = 628  # Can recruit 7 per slot
BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_3 = 629  # Can recruit 10 per slot
BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_4 = 630  # Can recruit 15 per slot
BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_5 = 631  # Can recruit 20 per slot

########################
# Kingdoms
########################
KINGDOM_GREEN = 0
KINGDOM_SANDS = 1
KINGDOM_ICE = 2
KINGDOM_FIRE = 3
KINGDOM_BERIMOND = 10

########################
# RV Types
########################
RV_TYPE_WOOD = 0
RV_TYPE_STONE = 1
RV_TYPE_FOOD = 2

########################
# Speed
########################
#
# Speed values are based on stable level.
#
# no boost:                       -1
#
# level 1 stables: coin boost     1001
# level 1 stables: ruby boost     1002
# level 1 stables: max ruby boost 1003
#
# level 2 stables: coin boost     1004
# level 2 stables: ruby boost     1005
# level 2 stables: max ruby boost 1006
#
# level 3 stables: coin boost     1007
# level 3 stables: ruby boost     1008
# level 3 stables: max ruby boost 1009

SPEED_NO_BOOST = -1
SPEED_LVL_1_STABLE_COIN_BOOST = 1001
SPEED_LVL_1_STABLE_LOW_RUBY_BOOST = 1002
SPEED_LVL_1_STABLE_HIGH_RUBY_BOOST = 1003

SPEED_LVL_2_STABLE_COIN_BOOST = 1004
SPEED_LVL_2_STABLE_LOW_RUBY_BOOST = 1005
SPEED_LVL_2_STABLE_HIGH_RUBY_BOOST = 1006

SPEED_LVL_3_STABLE_COIN_BOOST = 1007
SPEED_LVL_3_STABLE_LOW_RUBY_BOOST = 1008
SPEED_LVL_3_STABLE_HIGH_RUBY_BOOST = 1009

# Berimond uses a special speeds (there exist the 2 ruby speed boosts as well but I've never used them).
# Never tested with no stables either
SPEED_LVL_BERIMOND_COIN_BOOST = 1021

SPEEDS = [[SPEED_NO_BOOST, SPEED_NO_BOOST, SPEED_NO_BOOST, SPEED_NO_BOOST], [SPEED_NO_BOOST, SPEED_LVL_1_STABLE_COIN_BOOST, SPEED_LVL_1_STABLE_LOW_RUBY_BOOST, SPEED_LVL_1_STABLE_HIGH_RUBY_BOOST], [SPEED_NO_BOOST, SPEED_LVL_2_STABLE_COIN_BOOST, SPEED_LVL_2_STABLE_LOW_RUBY_BOOST, SPEED_LVL_2_STABLE_HIGH_RUBY_BOOST], [SPEED_NO_BOOST, SPEED_LVL_3_STABLE_COIN_BOOST, SPEED_LVL_3_STABLE_LOW_RUBY_BOOST, SPEED_LVL_3_STABLE_HIGH_RUBY_BOOST]]

############################
# Time boosts
############################
TIME_BOOST_TYPE_24H = "MS7"
TIME_BOOST_TYPE_5H = "MS6"
TIME_BOOST_TYPE_1H = "MS5"
TIME_BOOST_TYPE_30M = "MS4"
TIME_BOOST_TYPE_10M = "MS3"
TIME_BOOST_TYPE_5M = "MS2"
TIME_BOOST_TYPE_1M = "MS1"

############################
# Feast types
############################

# None running
FEAST_LEVEL_NONE = -1

# 4K feast
FEAST_LEVEL_LOWEST_FEAST = 0

# 13K feast
FEAST_LEVEL_KNIGHTS_FEAST = -200000  # TODO

# 40K feast
FEAST_LEVEL_KINGS_FEAST = 2

# 80K feast
FEAST_LEVEL_ARISTOCRATIC_FEAST = 3

# Ruby Feast
FEAST_LEVEL_RUBY_FEAST = -100000  # TODO

##############################################################
# %gaa% response castle type ids
##############################################################
CASTLE_TYPE_HUMAN_MAIN = 1
CASTLE_TYPE_RBC = 2
CASTLE_TYPE_HUMAN_OP = 4
CASTLE_TYPE_FORTRESS = 11
CASTLE_TYPE_ROBBER_BARON_KING = 13
CASTLE_TYPE_BERIMOND_TOWER = 17
CASTLE_TYPE_FOREIGN_LEGION = 21
CASTLE_TYPE_ROYAL_TOWER = 23
CASTLE_TYPE_MONUMENT = 26
CASTLE_TYPE_NOMAD = 27  # Does not Require a call to GetMap()
# What is 31?
CASTLE_TYPE_SAMURAI = 33  # Requires a call to GetMap()

##############################################################
# Print mappings
##############################################################
TOOLS = {}
DEFENSIVE_TOOLS = {}
OFFENSIVE_TOOLS = {}

OFFENSIVE_TOOLS[TOOL_TYPE_KHAN_CHEST] = "KHAN CHEST"
OFFENSIVE_TOOLS[TOOL_TYPE_NOMAD_PIGGY_BANK] = "NOMAD PIGGY BANK"
OFFENSIVE_TOOLS[TOOL_TYPE_PREMIUM_PIGGY_BANK] = "PREMIUM PIGGY BANK"
OFFENSIVE_TOOLS[TOOL_TYPE_GOLDEN_PIGGY_BANK] = "GOLDEN PIGGY BANK"
OFFENSIVE_TOOLS[TOOL_TYPE_HEROES_BANNER] = "HEROES BANNER"
OFFENSIVE_TOOLS[TOOL_TYPE_SOLDIERS_BANNER] = "SOLDIERS BANNER"
OFFENSIVE_TOOLS[TOOL_TYPE_BATTERING_RAM] = "BATTERING RAM"
OFFENSIVE_TOOLS[TOOL_TYPE_LADDER] = "LADDER"
OFFENSIVE_TOOLS[TOOL_TYPE_SHADOW_RAM] = "SHADOW RAM"
OFFENSIVE_TOOLS[TOOL_TYPE_SHADOW_LADDER] = "SHADOW LADDER"
OFFENSIVE_TOOLS[TOOL_TYPE_WOOD_BUNDLE] = "WOOD BUNDLE"
OFFENSIVE_TOOLS[TOOL_TYPE_SHADOW_BUNDLES] = "SHADOW BUNDLES"
OFFENSIVE_TOOLS[TOOL_TYPE_SHADOW_SHIELDS] = "SHADOW SHIELDS"
OFFENSIVE_TOOLS[TOOL_TYPE_MANTLET] = "MANTLET"
DEFENSIVE_TOOLS[TOOL_TYPE_PORTCULLIS] = "PORTCULLIS"
DEFENSIVE_TOOLS[TOOL_TYPE_ARROW_SLIT] = "ARROW SLIT"
DEFENSIVE_TOOLS[TOOL_TYPE_FIRE_MOAT] = "FIRE MOAT"
DEFENSIVE_TOOLS[TOOL_TYPE_CASTLE_GATE_REINFORCEMENT] = "CASTLE GATE REINFORCEMENT"
DEFENSIVE_TOOLS[TOOL_TYPE_MURDER_HOLE] = "MURDER HOLE"
DEFENSIVE_TOOLS[TOOL_TYPE_FLAMING_ARROWS] = "FLAMING ARROWS"
DEFENSIVE_TOOLS[TOOL_TYPE_SHARPENED_STAKES] = "SHARPENED STAKES"
OFFENSIVE_TOOLS[TOOL_TYPE_CAST_IRON_MANTLET] = "CAST IRON MANTLET"
DEFENSIVE_TOOLS[TOOL_TYPE_HURLING_ROCKS] = "HURLING ROCKS"
OFFENSIVE_TOOLS[TOOL_TYPE_SIEGE_TOWER] = "SIEGE TOWER"
OFFENSIVE_TOOLS[TOOL_TYPE_IRON_RAM] = "IRON RAM"
OFFENSIVE_TOOLS[TOOL_TYPE_ASSAULT_BRIDGE] = "ASSAULT BRIDGE"
DEFENSIVE_TOOLS[TOOL_TYPE_INSULATING_MAT] = "INSULATING MAT"
DEFENSIVE_TOOLS[TOOL_TYPE_BULWARK] = "BULWARK"
DEFENSIVE_TOOLS[TOOL_TYPE_SWAMP_SNAPPER] = "SWAMP SNAPPER"
DEFENSIVE_TOOLS[TOOL_TYPE_TAR_PITCH_KETTLE] = "TAR PITCH KETTLE"
OFFENSIVE_TOOLS[TOOL_TYPE_HEAVY_RAM] = "HEAVY RAM"
OFFENSIVE_TOOLS[TOOL_TYPE_BELFRY] = "BELFRY"
OFFENSIVE_TOOLS[TOOL_TYPE_BOULDERS] = "BOULDERS"
OFFENSIVE_TOOLS[TOOL_TYPE_SHIELD_WALL] = "SHIELD WALL"
OFFENSIVE_TOOLS[TOOL_TYPE_LOOT_SACK] = "LOOT SACK"
OFFENSIVE_TOOLS[TOOL_TYPE_LOOT_CART] = "LOOT CART"
OFFENSIVE_TOOLS[TOOL_TYPE_BANNER] = "BANNER"
OFFENSIVE_TOOLS[TOOL_TYPE_GLORY_BANNER] = "GLORY BANNER"
DEFENSIVE_TOOLS[TOOL_TYPE_LIME_POWDER_BOMB] = "LIME POWDER BOMB"
DEFENSIVE_TOOLS[TOOL_TYPE_BODKIN_ARROWHEADS] = "BODKIN ARROWHEADS"
OFFENSIVE_TOOLS[TOOL_TYPE_HORSETAIL_STANDARD] = "HORSETAIL STANDARD"
OFFENSIVE_TOOLS[TOOL_TYPE_WAR_HORN] = "WAR HORN"

OFFENSIVE_TOOLS[TOOL_TYPE_SHADOW_LADDER] = "SHADOW LADDER"


OFFENSIVE_TOOLS[TOOL_TYPE_TURTLE_RAM] = 'TURTLE RAM'
OFFENSIVE_TOOLS[TOOL_TYPE_SPIKED_SHIELD] = 'SPIKED SHIELD'
OFFENSIVE_TOOLS[TOOL_TYPE_SWIVELING_SHIELD] = 'SWIVELING SHIELD'
OFFENSIVE_TOOLS[TOOL_TYPE_FOLDING_LADDER] = 'FOLDING LADDER'
OFFENSIVE_TOOLS[TOOL_TYPE_GATE_STORMER] = 'GATE STORMER'
OFFENSIVE_TOOLS[TOOL_TYPE_THE_WOLFS_HOWL] = 'THE WOLFS HOWL'
OFFENSIVE_TOOLS[TOOL_TYPE_SAMURAI_BANNER] = 'SAMURAI BANNER'
OFFENSIVE_TOOLS[TOOL_TYPE_TONNELON] = 'TONNELON'
OFFENSIVE_TOOLS[TOOL_TYPE_THE_SPLENDOR_OF_BERIMOND] = 'THE SPLENDOR OF BERIMOND'
OFFENSIVE_TOOLS[TOOL_TYPE_BANNER_OF_TRIUMPH] = 'BANNER OF TRIUMPH'
OFFENSIVE_TOOLS[TOOL_TYPE_INVADER_RAM] = 'INVADER_RAM'
OFFENSIVE_TOOLS[TOOL_TYPE_SMOKE_BOMB] = 'SMOKE BOMB'

OFFENSIVE_TOOLS[TOOL_TYPE_SHIELD_SLED] = 'SHIELD SLED'
OFFENSIVE_TOOLS[TOOL_TYPE_BANNER_OF_THE_FROST_WARRIORS] = 'BANNER OF THE FROST WARRIORS'
OFFENSIVE_TOOLS[TOOL_TYPE_THE_WINTER_KINGS_BANNER] = "THE WINTER KING'S BANNER"

OFFENSIVE_TOOLS[TOOL_TYPE_INVADER_LADDER] = 'INVADER LADDER'
OFFENSIVE_TOOLS[TOOL_TYPE_INVADER_MASK] = 'INVADER MASK'
OFFENSIVE_TOOLS[TOOL_TYPE_BANNER_OF_THE_FOREIGN_INVADERS] = 'BANNER OF THE FOREIGN INVADERS'
OFFENSIVE_TOOLS[TOOL_TYPE_THE_CLAW] = 'THE CLAW'
OFFENSIVE_TOOLS[TOOL_TYPE_PAW_LADDER] = 'PAW LADDER'
OFFENSIVE_TOOLS[TOOL_TYPE_BERIMOND_SHIELD] = 'BERIMOND SHIELD'
OFFENSIVE_TOOLS[TOOL_TYPE_THE_GLORY_OF_BERIMOND] = 'THE GLORY OF BERIMOND'


TOOLS.update(DEFENSIVE_TOOLS)
TOOLS.update(OFFENSIVE_TOOLS)

TROOPS = {}
DEFENSIVE_TROOPS = {}
OFFENSIVE_TROOPS = {}

OFFENSIVE_TROOPS[TROOP_TYPE_VET_SABER_CLEAVER] = "VET SABER CLEAVER"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_SLINGSHOT] = "VET SLINGSHOT"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_DEMON_HORROR] = "VET DEMON HORROR"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_DEATHLY_HORROR] = "VET DEATHLY HORROR"
DEFENSIVE_TROOPS[TROOP_TYPE_VET_FLAME_BEARER] = "VET FLAME BEARER"
DEFENSIVE_TROOPS[TROOP_TYPE_VET_COMPOSITE_BOWMAN] = "VET COMPOSITE BOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_FOREST_WARRIOR] = "FOREST WARRIOR"
OFFENSIVE_TROOPS[TROOP_TYPE_SPEAR_WOMAN] = "SPEAR WOMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_MUSCLE_MAN] = "MUSCLE MAN"  # Berimond melee
OFFENSIVE_TROOPS[TROOP_TYPE_MARKSMAN] = "MARKSMAN"  # Berimond range
OFFENSIVE_TROOPS[TROOP_TYPE_IMPERIAL_GUARDSMAN] = "IMPERIAL GUARDSMAN"  # Berimond range
OFFENSIVE_TROOPS[TROOP_TYPE_IMPERIAL_BOWMAN] = "IMPERIAL BOWMAN"  # Berimond range
OFFENSIVE_TROOPS[TROOP_TYPE_BERSERKER] = "BERSERKER"
DEFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_KATANA_WARRIOR] = "RENEGADE KATANA WARRIOR"  # Samurai melee defender
DEFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_BOW_MASTER] = "RENEGADE BOW MASTER"  # Samurai range defender
OFFENSIVE_TROOPS[TROOP_TYPE_ELITE_SKELETON_WARRIOR] = "ELITE SKELETON WARRIOR"
OFFENSIVE_TROOPS[TROOP_TYPE_ELITE_SKELETON_BOWMAN] = "ELITE SKELETON BOWMAN"

OFFENSIVE_TROOPS[TROOP_TYPE_BONE_HUNTRESS] = "BONE HUNTRESS"
OFFENSIVE_TROOPS[TROOP_TYPE_FROST_BOWMAN]  = "FROST BOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_MASTER_BONE_HUNTRESS] = "MASTER BONE HUNTRESS"
OFFENSIVE_TROOPS[TROOP_TYPE_MASTER_FROST_BOWMAN] = "MASTER FROST BOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_ELITE_KNIGHT] = "ELITE KNIGHT"
OFFENSIVE_TROOPS[TROOP_TYPE_ELITE_CROSSBOWMAN] = "ELITE CROSSBOWMAN"

DEFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_SAI_WARRIOR] = "RENEGADE SAI WARRIOR"
DEFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_ARROW_THROWER] = "RENEGADE ARROW THROWER"

DEFENSIVE_TROOPS[TROOP_TYPE_VET_HALBERDIER] = "VET HALBERDIER"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_TWO_HANDED_SWORDSMAN] = "VET TWO HANDED SWORDSMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_LONGBOWMAN] = "VET LONGBOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_HEAVY_CROSSBOWMAN] = "VET HEAVY CROSSBOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_SWORDSMAN] = "SWORDSMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_SPEARMAN] = "SPEARMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_MACEMAN] = "MACEMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_HALBERDIER] = "HALBERDIER"
OFFENSIVE_TROOPS[TROOP_TYPE_TWO_HANDED_SWORDSMAN] = "TWO HANDED SWORDSMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_ARCHER] = "ARCHER"
OFFENSIVE_TROOPS[TROOP_TYPE_CROSSBOWMAN] = "CROSSBOWMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_BOWMAN] = "BOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_HEAVY_CROSSBOWMAN] = "HEAVY CROSSBOWMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_LONGBOWMAN] = "LONGBOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_PYROMANIAC] = "PYROMANIAC"
DEFENSIVE_TROOPS[TROOP_TYPE_KINGSGUARD_ROYAL_SENTINEL] = "KINGSGUARD ROYAL SENTINEL"
DEFENSIVE_TROOPS[TROOP_TYPE_KINGSGUARD_ROYAL_SCOUT] = "KINGSGUARD ROYAL SCOUT"

OFFENSIVE_TROOPS[TROOP_TYPE_MARAUDER] = "MARAUDER"
# Sand RBC defenders (cannot own them)
DEFENSIVE_TOOLS[TROOP_TYPE_SABER_WARRIOR] = "SABER WARRIOR"
DEFENSIVE_TOOLS[TROOP_TYPE_DESERT_BOWMAN] = "DESERT BOWMAN"

OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_SABER_WARRIOR] = "RENEGADE SABER WARRIOR"
OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_DESERT_BOWMAN] = "RENEGADE DESERT BOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_NORSEMAN_WARRIOR] = "RENEGADE NORSEMAN WARRIOR"
OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_NORSEMAN_BOWMAN] = "RENEGADE NORSEMAN BOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_CULTIST_WARRIOR] = "RENEGADE CULTIST WARRIOR"
OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_CULTIST_BOWMAN] = "RENEGADE CULTIST BOWMAN"

OFFENSIVE_TROOPS[TROOP_TYPE_SHADOW_MACEMAN] = "SHADOW MACEMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_SHADOW_CROSSBOWAN] = "SHADOW CROSSBOWAN"
DEFENSIVE_TROOPS[TROOP_TYPE_VET_SPEARMAN] = "VET SPEARMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_MACEMAN] = "VET MACEMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_VET_BOWMAN] = "VET BOWMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_DUMMY_MELEE_SOLDIER] = "DUMMY MELEE SOLDIER"
DEFENSIVE_TROOPS[TROOP_TYPE_DUMMY_RANGED_SOLDIER] = "DUMMY RANGED SOLDIER"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_CROSSBOWMAN] = "VET CROSSBOWMAN"
DEFENSIVE_TROOPS[TROOP_TYPE_DUMMY_ARCHERS] = "DUMMY ARCHERS"
OFFENSIVE_TROOPS[TROOP_TYPE_TRAVELING_CROSSBOWMAN] = "TRAVELING CROSSBOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_TRAVELING_KNIGHT] = "TRAVELING KNIGHT"
OFFENSIVE_TROOPS[TROOP_TYPE_KINGSGUARD_BOW] = "KINGSGUARD BOW"
OFFENSIVE_TROOPS[TROOP_TYPE_SHADOW_ROGUE] = "SHADOW ROGUE"
OFFENSIVE_TROOPS[TROOP_TYPE_SHADOW_FELON] = "SHADOW FELON"
OFFENSIVE_TROOPS[TROOP_TYPE_KINGSGUARD_KNIGHT] = "KINGSGUARD KNIGHT"
OFFENSIVE_TROOPS[TROOP_TYPE_DEMON_HORROR] = "DEMON HORROR"
OFFENSIVE_TROOPS[TROOP_TYPE_DEATHLY_HORROR] = "DEATHLY HORROR"
# OFFENSIVE_TROOPS[TROOP_TYPE_BARBARIAN] = "FAST MARAUDER"
OFFENSIVE_TROOPS[TROOP_TYPE_BARBARIAN] = "BARBARIAN"
OFFENSIVE_TROOPS[TROOP_TYPE_COMPOSITE_BOWMAN] = "COMPOSITE BOWMAN"
OFFENSIVE_TROOPS[TROOP_TYPE_FLAME_BEARER] = "FLAME BEARER"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_SWORDMAN] = "VET SWORDMAN"

OFFENSIVE_TROOPS[TROOP_TYPE_KHAN_GUARDS] = "KHAN GUARDS"
OFFENSIVE_TROOPS[TROOP_TYPE_SABER_CLEAVER] = "SABER CLEAVER"
OFFENSIVE_TROOPS[TROOP_TYPE_SLINGSHOT] = "SLINGSHOT"
OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_SPEAR_THROWER] = "RENEGADE SPEAR THROWER"

DEFENSIVE_TROOPS[TROOP_TYPE_LANCE] = "LANCE"
DEFENSIVE_TROOPS[TROOP_TYPE_SPEAR_THROWER] = "TROOP TYPE SPEAR THROWER"

OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_SWASHBUCKLER] = "RENEGADE SWASHBUCKLER"
OFFENSIVE_TROOPS[TROOP_TYPE_RENEGADE_SAIL_RIPPER] = "RENEGADE SAIL RIPPER"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_MARAUDER] = "VET MARAUDER"
OFFENSIVE_TROOPS[TROOP_TYPE_VET_PYROMANIAC] = "VET PYROMANIAC"

TROOPS.update(DEFENSIVE_TROOPS)
TROOPS.update(OFFENSIVE_TROOPS)

BUILDINGS = {}
BUILDINGS[BUILDING_HOSPITAL_LEVEL_1] = "BUILDING HOSPITAL LEVEL 1"
BUILDINGS[BUILDING_HOSPITAL_LEVEL_2] = "BUILDING HOSPITAL LEVEL 2"
BUILDINGS[BUILDING_HOSPITAL_LEVEL_3] = "BUILDING HOSPITAL LEVEL 3"

BUILDINGS[BUILDING_STONE_QUARRY_LEVEL_1] = "STONE QUARRY LEVEL 1"
BUILDINGS[BUILDING_STONE_QUARRY_LEVEL_2] = "STONE QUARRY LEVEL 2"
BUILDINGS[BUILDING_STONE_QUARRY_LEVEL_3] = "STONE QUARRY LEVEL 3"
BUILDINGS[BUILDING_STONE_QUARRY_LEVEL_4] = "STONE QUARRY LEVEL 4"
BUILDINGS[BUILDING_STONE_QUARRY_LEVEL_7] = "STONE QUARRY LEVEL 7"
BUILDINGS[BUILDING_STONE_QUARRY_LEVEL_9] = "STONE QUARRY LEVEL 9"
BUILDINGS[BUILDING_STONE_QUARRY_LEVEL_10] = "STONE QUARRY LEVEL 10"

BUILDINGS[BUILDING_FARMHOUSE_LEVEL_1] = "FARM LEVEL 1"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_2] = "FARM LEVEL 2"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_3] = "FARM LEVEL 3"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_4] = "FARM LEVEL 4"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_5] = "FARM LEVEL 5"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_6] = "FARM LEVEL 6"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_7] = "FARM LEVEL 7"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_8] = "FARM LEVEL 8"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_9] = "FARM LEVEL 9"
BUILDINGS[BUILDING_FARMHOUSE_LEVEL_10] = "FARM LEVEL 10"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_1] = "WOOD CUTTER LEVEL 1"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_3] = "WOOD CUTTER LEVEL 3"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_4] = "WOOD CUTTER LEVEL 4"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_5] = "WOOD CUTTER LEVEL 5"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_6] = "WOOD CUTTER LEVEL 6"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_7] = "WOOD CUTTER LEVEL 7"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_8] = "WOOD CUTTER LEVEL 8"
BUILDINGS[BUILDING_WOOD_CUTTER_LEVEL_9] = "WOOD CUTTER LEVEL 9"

BUILDINGS[BUILDING_DWELLING_LEVEL_1] = "DWELLING LEVEL 1"
BUILDINGS[BUILDING_DWELLING_LEVEL_2] = "DWELLING LEVEL 2"
BUILDINGS[BUILDING_DWELLING_LEVEL_3] = "DWELLING LEVEL 3"
BUILDINGS[BUILDING_DWELLING_LEVEL_5] = "DWELLING LEVEL 5"
BUILDINGS[BUILDING_DWELLING_LEVEL_6] = "DWELLING LEVEL 6"
BUILDINGS[BUILDING_DWELLING_LEVEL_10] = "DWELLING LEVEL 10"

BUILDINGS[BUILDING_TOWNHOUSE_LEVEL_11] = "TOWNHOUSE LEVEL 11"

BUILDINGS[BUILDING_SAW_MILL_LEVEL_1] = "SAW MILL LEVEL 1"
BUILDINGS[BUILDING_SAW_MILL_LEVEL_2] = "SAW MILL LEVEL 2"

BUILDINGS[BUILDING_STONE_MASON_LEVEL_1] = "STONE MASON LEVEL 1"

BUILDINGS[BUILDING_BAKERY_LEVEL_4] = "BAKERY_LEVEL_4"

BUILDINGS[BUILDING_ESTATE_LEVEL_1] = "ESTATE LEVEL 1"

BUILDINGS[BUILDING_GUARD_HOUSE_LEVEL_1] = "GUARD HOUSE LEVEL 1"
BUILDINGS[BUILDING_GUARD_HOUSE_LEVEL_2] = "GUARD HOUSE LEVEL 2"
BUILDINGS[BUILDING_GUARD_HOUSE_LEVEL_3] = "GUARD HOUSE LEVEL 3"

BUILDINGS[BUILDING_WATCHTOWER_LEVEL_5] = "WATCHTOWER LEVEL 5"

BUILDINGS[BUILDING_FLOUR_MILL_LEVEL_1] = "FLOUR MILL LEVEL 1"
BUILDINGS[BUILDING_FLOUR_MILL_LEVEL_2] = "FLOUR MILL LEVEL 2"
BUILDINGS[BUILDING_FLOUR_MILL_LEVEL_3] = "FLOUR MILL LEVEL 3"
BUILDINGS[BUILDING_FLOUR_MILL_LEVEL_6] = "FLOUR MILL LEVEL 6"

BUILDINGS[BUILDING_STORE_HOUSE_LEVEL_1] = "STORE HOUSE LEVEL 1"
BUILDINGS[BUILDING_STORE_HOUSE_LEVEL_2] = "STORE HOUSE LEVEL 2"
BUILDINGS[BUILDING_STORE_HOUSE_LEVEL_3] = "STORE HOUSE LEVEL 3"

BUILDINGS[BUILDING_MARKET_PLACE_LEVEL_1] = "MARKET PLACE LEVEL 1"
BUILDINGS[BUILDING_MARKET_PLACE_LEVEL_4] = "MARKET PLACE LEVEL 4"
BUILDINGS[BUILDING_MARKET_PLACE_LEVEL_6] = "MARKET PLACE LEVEL 6"
BUILDINGS[BUILDING_MARKET_PLACE_LEVEL_7] = "MARKET PLACE LEVEL 7"

BUILDINGS[BUILDING_BARRACKS_LEVEL_1] = "BARRACKS LEVEL 1"
BUILDINGS[BUILDING_BARRACKS_LEVEL_2] = "BARRACKS LEVEL 2"
BUILDINGS[BUILDING_BARRACKS_LEVEL_3] = "BARRACKS LEVEL 3"
BUILDINGS[BUILDING_BARRACKS_LEVEL_4] = "BARRACKS LEVEL 4"
BUILDINGS[BUILDING_BARRACKS_LEVEL_5] = "BARRACKS LEVEL 5"

BUILDINGS[BUILDING_ENCAMPMENT_LEVEL_1] = "BUILDING ENCAMPMENT LEVEL 1"
BUILDINGS[BUILDING_TAVERN_LEVEL_1] = "TAVERN LEVEL 1"
BUILDINGS[BUILDING_TAVERN_LEVEL_3] = "TAVERN LEVEL 3"

BUILDINGS[BUILDING_SIEGE_WORKSHOP_LEVEL_1] = "SIEGE WORKSHOP LEVEL 1"
BUILDINGS[BUILDING_SIEGE_WORKSHOP_LEVEL_2] = "SIEGE WORKSHOP LEVEL 2"
BUILDINGS[BUILDING_SIEGE_WORKSHOP_LEVEL_3] = "SIEGE WORKSHOP LEVEL 3"
BUILDINGS[BUILDING_DEFENSE_WORKSHOP_LEVEL_1] = "DEFENSE WORKSHOP LEVEL 1"
BUILDINGS[BUILDING_KEEP_LEVEL_1] = "KEEP LEVEL 1"
BUILDINGS[BUILDING_KEEP_LEVEL_2] = "KEEP LEVEL 2"
BUILDINGS[BUILDING_KEEP_LEVEL_3] = "KEEP LEVEL 3"
BUILDINGS[BUILDING_KEEP_LEVEL_4] = "KEEP LEVEL 4"
BUILDINGS[BUILDING_STABLES_LEVEL_1] = "STABLES LEVEL 1"
BUILDINGS[BUILDING_STABLES_LEVEL_2] = "STABLES LEVEL 2"
BUILDINGS[BUILDING_STABLES_LEVEL_3] = "STABLES LEVEL 3"
BUILDINGS[BUILDING_LOOT_WAREHOUSE] = "LOOT WAREHOUSE"

BUILDINGS[BUILDING_STORE_HOUSE_LEVEL_7] = "STORE HOUSE LEVEL 7"

BUILDINGS[BUILDING_DECO_SUPPLIES] = "DECO SUPPLIES"
BUILDINGS[BUILDING_DECO_WITCH_WELL] = "DECO WITCH WELL"
BUILDINGS[BUILDING_DECO_SIGNPOST] = "DECO SIGNPOST"
BUILDINGS[BUILDING_DECO_PILLORY] = "DECO PILLORY"
BUILDINGS[BUILDING_DECO_SUNDIAL] = "DECO SUNDIAL"
BUILDINGS[BUILDING_DECO_FESTIVAL_SQUARE] = "DECO FESTIVAL SQUARE"
BUILDINGS[BUILDING_DECO_CASTLE_GARDEN] = "DECO CASTLE GARDEN"
BUILDINGS[BUILDING_DECO_MARKET_STALL] = "DECO MARKET STALL"
BUILDINGS[BUILDING_DECO_COLOSSUS] = "DECO COLOSSUS"
BUILDINGS[BUILDING_DECO_DRAGON_FOUNTAIN] = "DECO DRAGON FOUNTAIN"

BUILDINGS[BUILDING_GLASS_FURNACE_LEVEL_3] = "GLASS FURNACE_LEVEL 3"
BUILDINGS[BUILDING_GRANARY_LEVEL_10] = "GRANARY LEVEL 10"
BUILDINGS[BUILDING_HUNTING_LODGE_LEVEL_1] = "HUNTING LODGE LEVEL 1"


BUILDINGS[BUILDING_BLADE_COAST_SMALL_TENTS_LEVEL_1] = "BLADE COAST SMALL TENTS LEVEL 1"
BUILDINGS[BUILDING_BLADE_COAST_SMALL_TENTS_LEVEL_2] = "BLADE COAST SMALL TENTS LEVEL 2"
BUILDINGS[BUILDING_BLADE_COAST_DRILL_GROUND] = "BLADE COAST DRILL GROUND"
BUILDINGS[BUILDING_BLADE_COAST_MAIN] = "BLADE COAST MAIN"
BUILDINGS[BUILDING_BLADE_COAST_STOREHOUSE] = "BLADE COAST STOREHOUSE"

BUILDINGS[BUILDING_BERIMOND_LARGE_TENTS_LEVEL_1] = "BERIMOND LARGE TENTS LEVEL 1"
# BUILDINGS[BUILDING_BERIMOND_SMALL_TENTS_LEVEL_1] = "BERIMOND SMALL TENTS LEVEL 1"
BUILDINGS[BUILDING_BERIMOND_SMALL_TENTS_LEVEL_2] = "BERIMOND SMALL TENTS LEVEL 2"
BUILDINGS[BUILDING_BERIMOND_SMALL_TENTS_LEVEL_3] = "BERIMOND SMALL TENTS LEVEL 3"
BUILDINGS[BUILDING_BERIMOND_SMALL_TENTS_LEVEL_4] = "BERIMOND SMALL TENTS LEVEL 4"
BUILDINGS[BUILDING_BERIMOND_SUPPLY_STOREHOUSE_LEVEL_1] = "BERIMOND SUPPLY STOREHOUSE LEVEL 1"
BUILDINGS[BUILDING_BERIMOND_STABLES_LEVEL_1] = "BERIMOND STABLES LEVEL 1"
BUILDINGS[BUILDING_BERIMOND_MARKET_PLACE_LEVEL_1] = "BERIMOND MARKET PLACE LEVEL 1"
BUILDINGS[BUILDING_BERIMOND_MAIN_TENT] = "BERIMOND MAIN TENT"
BUILDINGS[BUILDING_BERIMOND_ARSENAL] = "BERIMOND ARSENAL"
BUILDINGS[BUILDING_BERIMOND_FIELD_KITCHEN] = "BERIMOND FIELD KITCHEN"
BUILDINGS[BUILDING_BERIMOND_FIELD_HOSPITAL_LEVEL_1] = "BERIMOND FIELD HOSPITAL LEVEL 1"
BUILDINGS[BUILDING_BERIMOND_FIELD_HOSPITAL_LEVEL_2] = "BERIMOND FIELD HOSPITAL LEVEL 2"
BUILDINGS[BUILDING_BERIMOND_HEADQUARTERS_LEVEL_2] = "BERIMOND HEADQUARTERS LEVEL 2"
BUILDINGS[BUILDING_BERIMOND_HEADQUARTERS_LEVEL_3] = "BERIMOND HEADQUARTERS LEVEL 3"
BUILDINGS[BUILDING_BERIMOND_HEADQUARTERS_LEVEL_5] = "BERIMOND HEADQUARTERS LEVEL 5"
BUILDINGS[BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_1] = "BERIMOND TRAINING GROUNDS LEVEL 1"
BUILDINGS[BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_2] = "BERIMOND TRAINING GROUNDS LEVEL 2"
BUILDINGS[BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_3] = "BERIMOND TRAINING GROUNDS LEVEL 3"
BUILDINGS[BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_4] = "BERIMOND TRAINING GROUNDS LEVEL 4"
BUILDINGS[BUILDING_BERIMOND_TRAINING_GROUNDS_LEVEL_5] = "BERIMOND TRAINING GROUNDS LEVEL 5"


def is_known(toolOrTroopID):
    b = int(toolOrTroopID)
    return b in TOOLS or b in TROOPS


def is_tool(toolOrTroopID):
    return int(toolOrTroopID) in TOOLS


def is_troop(toolOrTroopID):
    return int(toolOrTroopID) in TROOPS


def max_baron_level(kingdomID):
    maxedBaronLevel = -1
    if kingdomID == KINGDOM_ICE:
        maxedBaronLevel = 154
    elif kingdomID == KINGDOM_SANDS:
        maxedBaronLevel = 112
    elif kingdomID == KINGDOM_FIRE:
        maxedBaronLevel = 112
    else:
        print ("TODO Max level for green?")

    return maxedBaronLevel


def tools_and_troops_to_string(toolOrTroopID):
    b = int(toolOrTroopID)
    if b in TROOPS:
        return TROOPS[b]
    if b in TOOLS:
        return TOOLS[b]
    return "UNKNOWN TOOL/TROOP ID {}".format(str(b))


def building_to_string(buildingID):
    b = int(buildingID)
    if b in BUILDINGS:
        return BUILDINGS[b]
    return "UNKNOWN BUILDING ID {}".format(str(b))


def kingdom_to_string(kingdomID):
    if kingdomID == KINGDOM_GREEN:
        return "Green"
    elif kingdomID == KINGDOM_ICE:
        return "Ice"
    elif kingdomID == KINGDOM_FIRE:
        return "Fire"
    elif kingdomID == KINGDOM_SANDS:
        return "Sands"
    elif kingdomID == KINGDOM_BERIMOND:
        return "Berimond"
    return "Invalid " + str(kingdomID)


def kingdom_from_string(kingdomName):
    kn = kingdomName.lower()
    if kn == "green":
        return KINGDOM_GREEN
    elif kn == "ice":
        return KINGDOM_ICE
    elif kn == "sand" or kn == "sands":
        return KINGDOM_SANDS
    elif kn == "fire":
        return KINGDOM_FIRE
    elif kn == "berimond":
        return KINGDOM_BERIMOND
    else:
        raise ValueError


# parser.add_argument('-i', '--kid', choices=['ice', 'sand', 'fire'], help='Kingdom')

def rv_type_to_string(rvType):
    if rvType == RV_TYPE_FOOD:
        return 'Food'
    elif rvType == RV_TYPE_WOOD:
        return 'Wood'
    elif rvType == RV_TYPE_STONE:
        return "Stone"
    return "Invalid"


def castle_type_to_string(kingdomID, castleOrOutpostType):
    if kingdomID == KINGDOM_GREEN:
        if castleOrOutpostType == 1:
            return "Green Main"
        elif castleOrOutpostType == 4:
            return "Green Outpost"
            # return "Shiny (8-2) Food Op"  # This might not be unique, don't have values for other op types or 6-2 variants
    elif kingdomID == KINGDOM_ICE:
        return "Ice Main"
    elif kingdomID == KINGDOM_FIRE:
        return "Fire Main"
    elif kingdomID == KINGDOM_SANDS:
        return "Sands Main"
    elif kingdomID == KINGDOM_BERIMOND:
        return "Berimond Encampment"


def feast_to_string(feastType):

    if feastType == FEAST_LEVEL_NONE:
        return "None"

    if feastType == FEAST_LEVEL_LOWEST_FEAST:
        return "4k feast"

    if feastType == FEAST_LEVEL_KINGS_FEAST:
        return "King's feast (40k)"

    if feastType == FEAST_LEVEL_ARISTOCRATIC_FEAST:
        return "Aristocratic feast (80k)"

    if feastType == FEAST_LEVEL_RUBY_FEAST:
        return "Ruby feast"

    if feastType == FEAST_LEVEL_KNIGHTS_FEAST:
        return "Knights feast (13k)"


##########################
# Equipment
##########################

# Castellan attribute/bonus/property ids for eq
#  2:  Travel speed during conquest
#  3:  Resources lost when looting
#  4:  Early discovery of attacks
#  5:  Fires when looting
#  6:  Required occupation time during capture attacks
#  7:  Wall protection
#  8:  Gate protection
#  9:  Moat protection
#  10: Combat strength of melee soldiers
#  11: Combat strength of range soldiers
#  ??: Glory in defense
#
# Commander attribute/bonus/property ids for eq
#  52: Honor points
#  53: Travel speed
#  54: Resources when looting
#  55: Late discovery of the army by the target
#  56: Fires when looting
#  57: Wall protection of enemy
#  58: Gate protection of enemy
#  59: Moat protection of enemy
#  60: Chance of finding stronger equipment
#  61: Melee strength
#  62: Range strength
#  63: Chance of destroying enemy buildings
#  64: Travel cost
#  242: Travel speed of the army when attacking NPC targets (HERO)
#  306: Soldier limit on the front when attacking NPC targets (HERO)
#  231: Combat strength in attacks against main castles, castles in kingdoms, and foreign castles
#  332: Moat protection of the attacked castle lord
#  >>>>>>>>>>> 19-11-2016: TODO there are now bonuses for CY on normal EQ not just on heroes

EQ_BONUS_CASTELLAN_GLORY_POINTS_IN_DEFENSE = 1
EQ_BONUS_CASTELLAN_TRAVEL_SPEED_DURING_CONQUEST = 2
EQ_BONUS_CASTELLAN_RESOURCES_LOST_WHEN_LOOTING  = 3
EQ_BONUS_CASTELLAN_EARLY_DISCOVERY_OF_ATTACKS   = 4
EQ_BONUS_CASTELLAN_FIRES_WHEN_LOOTING           = 5
EQ_BONUS_CASTELLAN_REQUIRED_OCCUPATION_TIME_DURING_CAPTURE_ATTACKS = 6
EQ_BONUS_CASTELLAN_WALL_PROTECTION = 7
EQ_BONUS_CASTELLAN_GATE_PROTECTION = 8
EQ_BONUS_CASTELLAN_MOAT_PROTECTION = 9
EQ_BONUS_CASTELLAN_COMBAT_STRENGTH_OF_MELEE_SOLDIERS = 10
EQ_BONUS_CASTELLAN_COMBAT_STRENGTH_OF_RANGE_SOLDIERS = 11
# EQ_BONUS_CASTELLAN_GLORY_IN_DEFENSE = ??

EQ_BONUS_COMMANDER_GLORY_POINTS = 51
EQ_BONUS_COMMANDER_HONOR_POINTS = 52
EQ_BONUS_COMMANDER_TRAVEL_SPEED = 53
EQ_BONUS_COMMANDER_RESOURCES_WHEN_LOOTING = 54
EQ_BONUS_COMMANDER_LATE_DISCOVERY_OF_THE_ARMY_BY_THE_TARGET = 55
EQ_BONUS_COMMANDER_FIRES_WHEN_LOOTING = 56
EQ_BONUS_COMMANDER_WALL_PROTECTION_OF_ENEMY = 57
EQ_BONUS_COMMANDER_GATE_PROTECTION_OF_ENEMY = 58
EQ_BONUS_COMMANDER_MOAT_PROTECTION_OF_ENEMY = 59
EQ_BONUS_COMMANDER_CHANCE_OF_FINDING_STRONGER_EQUIPMENT = 60
EQ_BONUS_COMMANDER_MELEE_STRENGTH = 61
EQ_BONUS_COMMANDER_RANGE_STRENGTH = 62
EQ_BONUS_COMMANDER_CHANCE_OF_DESTROYING_ENEMY_BUILDINGS = 63
EQ_BONUS_COMMANDER_TRAVEL_COST = 64

# This is a castellan hero bonus and seems to be more of an offensive bonus
EQ_BONUS_CASTELLAN_HERO__COMBAT_STRENGTH_OF_ATTACKERS_IN_THE_TARGETS_COURTYARDS_DURING_CAPTURE_ATTACKS = 214

# This is a castellan hero bonus and is a defensive bonus
EQ_BONUS_CASTELLAN_HERO__COMBAT_STRENGTH_OF_DEFENDERS_IN_THE_COURTYARD = 208

# This is a castellan hero bonus and is a defensive bonus
# This goes in the negative (ie: 5 is really -5)
EQ_BONUS_CASTELLAN_HERO__GATE_PROTECTION_WHILE_DEFENDING = 302

# This is a castellan hero bonus and seems to be more of an offensive bonus
EQ_BONUS_CASTELLAN_HERO__OCCUPATION_TIME_AS_CAPTOR = 325


EQ_BONUS_COMMANDER_HERO__WALL_PROTECTION_OF_THE_ENEMY_DURING_OCCUPATIONS = 228
EQ_BONUS_COMMANDER_HERO__COMBAT_STRENGTH_IN_ATTACKS_AGAINST_MAIN_CASTLES__CASTLES_IN_KINGDOMS__AND_FOREIGN_CASTLES = 231
EQ_BONUS_COMMANDER_HERO__TRAVEL_SPEED_OF_THE_ARMY_WHEN_ATTACKING_NPC_TARGETS = 242
EQ_BONUS_COMMANDER_HERO__TRAVEL_COST_WHEN_STATIONING_YOUR_TROOPS = 266
EQ_BONUS_COMMANDER_HERO__SOLDIER_LIMIT_ON_THE_FRONT_WHEN_ATTACKING_NPC_TARGETS = 306
EQ_BONUS_COMMANDER_HERO__GATE_PROTECTION_OF_NPC_TARGETS = 308
EQ_BONUS_COMMANDER_HERO__GATE_PROTECTION_OF_THE_ATTACKED_CASTLE_LORDS = 309
EQ_BONUS_COMMANDER_HERO__MOAT_PROTECTION_OF_THE_ATTACKED_CASTLE_LORD = 332


# This was found on a chest plate (but I assume it applies just the same on a hero)
EQ_BONUS_COMMANDER_COMBAT_STRENGTH_OF_ATTACKERS_IN_THE_COURTYARD = 334

EQ_BONUSES = {}
EQ_BONUSES[EQ_BONUS_CASTELLAN_GLORY_POINTS_IN_DEFENSE] = "EQ_BONUS_CASTELLAN_GLORY_POINTS_IN_DEFENSE"
EQ_BONUSES[EQ_BONUS_CASTELLAN_TRAVEL_SPEED_DURING_CONQUEST] = "EQ_BONUS_CASTELLAN_TRAVEL_SPEED_DURING_CONQUEST"
EQ_BONUSES[EQ_BONUS_CASTELLAN_RESOURCES_LOST_WHEN_LOOTING] = "EQ_BONUS_CASTELLAN_RESOURCES_LOST_WHEN_LOOTING"
EQ_BONUSES[EQ_BONUS_CASTELLAN_EARLY_DISCOVERY_OF_ATTACKS] = "EQ_BONUS_CASTELLAN_EARLY_DISCOVERY_OF_ATTACKS "
EQ_BONUSES[EQ_BONUS_CASTELLAN_FIRES_WHEN_LOOTING] = "EQ_BONUS_CASTELLAN_FIRES_WHEN_LOOTING"
EQ_BONUSES[EQ_BONUS_CASTELLAN_REQUIRED_OCCUPATION_TIME_DURING_CAPTURE_ATTACKS] = "EQ_BONUS_CASTELLAN_REQUIRED_OCCUPATION_TIME_DURING_CAPTURE_ATTACKS"
EQ_BONUSES[EQ_BONUS_CASTELLAN_WALL_PROTECTION] = "EQ_BONUS_CASTELLAN_WALL_PROTECTION"
EQ_BONUSES[EQ_BONUS_CASTELLAN_GATE_PROTECTION] = "EQ_BONUS_CASTELLAN_GATE_PROTECTION"
EQ_BONUSES[EQ_BONUS_CASTELLAN_MOAT_PROTECTION] = "EQ_BONUS_CASTELLAN_MOAT_PROTECTION"
EQ_BONUSES[EQ_BONUS_CASTELLAN_COMBAT_STRENGTH_OF_MELEE_SOLDIERS] = "EQ_BONUS_CASTELLAN_COMBAT_STRENGTH_OF_MELEE_SOLDIERS"
EQ_BONUSES[EQ_BONUS_CASTELLAN_COMBAT_STRENGTH_OF_RANGE_SOLDIERS] = "EQ_BONUS_CASTELLAN_COMBAT_STRENGTH_OF_RANGE_SOLDIERS"
# EQ_BONUSES[EQ_BONUS_CASTELLAN_GLORY_IN_DEFENSE] = "EQ_BONUS_CASTELLAN_GLORY_IN_DEFENSE"

EQ_BONUSES[EQ_BONUS_CASTELLAN_HERO__COMBAT_STRENGTH_OF_ATTACKERS_IN_THE_TARGETS_COURTYARDS_DURING_CAPTURE_ATTACKS] = "EQ_BONUS_CASTELLAN_HERO__COMBAT_STRENGTH_OF_ATTACKERS_IN_THE_TARGETS_COURTYARDS_DURING_CAPTURE_ATTACKS"
EQ_BONUSES[EQ_BONUS_CASTELLAN_HERO__COMBAT_STRENGTH_OF_DEFENDERS_IN_THE_COURTYARD] = "EQ_BONUS_CASTELLAN_HERO__COMBAT_STRENGTH_OF_DEFENDERS_IN_THE_COURTYARD"
EQ_BONUSES[EQ_BONUS_CASTELLAN_HERO__GATE_PROTECTION_WHILE_DEFENDING] = "EQ_BONUS_CASTELLAN_HERO__GATE_PROTECTION_WHILE_DEFENDING"
EQ_BONUSES[EQ_BONUS_CASTELLAN_HERO__OCCUPATION_TIME_AS_CAPTOR] = "EQ_BONUS_CASTELLAN_HERO__OCCUPATION_TIME_AS_CAPTOR"


EQ_BONUSES[EQ_BONUS_COMMANDER_GLORY_POINTS] = "EQ_BONUS_COMMANDER_GLORY_POINTS"
EQ_BONUSES[EQ_BONUS_COMMANDER_HONOR_POINTS] = "EQ_BONUS_COMMANDER_HONOR_POINTS"
EQ_BONUSES[EQ_BONUS_COMMANDER_TRAVEL_SPEED] = "EQ_BONUS_COMMANDER_TRAVEL_SPEED"
EQ_BONUSES[EQ_BONUS_COMMANDER_RESOURCES_WHEN_LOOTING] = "EQ_BONUS_COMMANDER_RESOURCES_WHEN_LOOTING"
EQ_BONUSES[EQ_BONUS_COMMANDER_LATE_DISCOVERY_OF_THE_ARMY_BY_THE_TARGET] = "EQ_BONUS_COMMANDER_LATE_DISCOVERY_OF_THE_ARMY_BY_THE_TARGET"
EQ_BONUSES[EQ_BONUS_COMMANDER_FIRES_WHEN_LOOTING] = "EQ_BONUS_COMMANDER_FIRES_WHEN_LOOTING"
EQ_BONUSES[EQ_BONUS_COMMANDER_WALL_PROTECTION_OF_ENEMY] = "EQ_BONUS_COMMANDER_WALL_PROTECTION_OF_ENEMY"
EQ_BONUSES[EQ_BONUS_COMMANDER_GATE_PROTECTION_OF_ENEMY] = "EQ_BONUS_COMMANDER_GATE_PROTECTION_OF_ENEMY"
EQ_BONUSES[EQ_BONUS_COMMANDER_MOAT_PROTECTION_OF_ENEMY] = "EQ_BONUS_COMMANDER_MOAT_PROTECTION_OF_ENEMY"
EQ_BONUSES[EQ_BONUS_COMMANDER_CHANCE_OF_FINDING_STRONGER_EQUIPMENT] = "EQ_BONUS_COMMANDER_CHANCE_OF_FINDING_STRONGER_EQUIPMENT"
EQ_BONUSES[EQ_BONUS_COMMANDER_MELEE_STRENGTH] = "EQ_BONUS_COMMANDER_MELEE_STRENGTH"
EQ_BONUSES[EQ_BONUS_COMMANDER_RANGE_STRENGTH] = "EQ_BONUS_COMMANDER_RANGE_STRENGTH"
EQ_BONUSES[EQ_BONUS_COMMANDER_CHANCE_OF_DESTROYING_ENEMY_BUILDINGS] = "EQ_BONUS_COMMANDER_CHANCE_OF_DESTROYING_ENEMY_BUILDINGS"
EQ_BONUSES[EQ_BONUS_COMMANDER_TRAVEL_COST] = "EQ_BONUS_COMMANDER_TRAVEL_COST"

EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__WALL_PROTECTION_OF_THE_ENEMY_DURING_OCCUPATIONS] = "EQ_BONUS_COMMANDER_HERO__WALL_PROTECTION_OF_THE_ENEMY_DURING_OCCUPATIONS"
EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__COMBAT_STRENGTH_IN_ATTACKS_AGAINST_MAIN_CASTLES__CASTLES_IN_KINGDOMS__AND_FOREIGN_CASTLES] = "EQ_BONUS_COMMANDER_HERO__COMBAT_STRENGTH_IN_ATTACKS_AGAINST_MAIN_CASTLES__CASTLES_IN_KINGDOMS__AND_FOREIGN_CASTLES"
EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__TRAVEL_SPEED_OF_THE_ARMY_WHEN_ATTACKING_NPC_TARGETS] = "EQ_BONUS_COMMANDER_HERO__TRAVEL_SPEED_OF_THE_ARMY_WHEN_ATTACKING_NPC_TARGETS"
EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__TRAVEL_COST_WHEN_STATIONING_YOUR_TROOPS] = "EQ_BONUS_COMMANDER_HERO__TRAVEL_COST_WHEN_STATIONING_YOUR_TROOPS"
EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__SOLDIER_LIMIT_ON_THE_FRONT_WHEN_ATTACKING_NPC_TARGETS] = "EQ_BONUS_COMMANDER_HERO__SOLDIER_LIMIT_ON_THE_FRONT_WHEN_ATTACKING_NPC_TARGETS"
EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__GATE_PROTECTION_OF_NPC_TARGETS] = "EQ_BONUS_COMMANDER_HERO__GATE_PROTECTION_OF_NPC_TARGETS"
EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__GATE_PROTECTION_OF_THE_ATTACKED_CASTLE_LORDS] = "EQ_BONUS_COMMANDER_HERO__GATE_PROTECTION_OF_THE_ATTACKED_CASTLE_LORDS"
EQ_BONUSES[EQ_BONUS_COMMANDER_HERO__MOAT_PROTECTION_OF_THE_ATTACKED_CASTLE_LORD] = "EQ_BONUS_COMMANDER_HERO__MOAT_PROTECTION_OF_THE_ATTACKED_CASTLE_LORD"
EQ_BONUSES[EQ_BONUS_COMMANDER_COMBAT_STRENGTH_OF_ATTACKERS_IN_THE_COURTYARD] = "EQ_BONUS_COMMANDER_COMBAT_STRENGTH_OF_ATTACKERS_IN_THE_COURTYARD"

def equipment_bonus_to_string(eqBonus):
    if eqBonus in EQ_BONUSES:
        return EQ_BONUSES[eqBonus]
    return "UNKNOWN EQ BONUS " + str(eqBonus)


ALL_ATTACK_RANGE_TROOPS = [TROOP_TYPE_KINGSGUARD_BOW,
                           TROOP_TYPE_ELITE_CROSSBOWMAN,
                           TROOP_TYPE_VET_CROSSBOWMAN,
                           TROOP_TYPE_VET_HEAVY_CROSSBOWMAN,
                           TROOP_TYPE_SLINGSHOT,
                           TROOP_TYPE_VET_SLINGSHOT,
                           TROOP_TYPE_RENEGADE_ARROW_THROWER,
                           TROOP_TYPE_RENEGADE_NORSEMAN_BOWMAN,
                           TROOP_TYPE_RENEGADE_DESERT_BOWMAN,
                           TROOP_TYPE_RENEGADE_CULTIST_BOWMAN,
                           TROOP_TYPE_DEATHLY_HORROR,
                           TROOP_TYPE_VET_DEATHLY_HORROR,
                           TROOP_TYPE_RENEGADE_SAIL_RIPPER,
                           TROOP_TYPE_MARKSMAN,
                           TROOP_TYPE_FROST_BOWMAN,
                           TROOP_TYPE_MASTER_FROST_BOWMAN
                           ]


ALL_ATTACK_MELEE_TROOP_TYPES = [TROOP_TYPE_VET_MACEMAN,
                                TROOP_TYPE_VET_TWO_HANDED_SWORDSMAN,
                                TROOP_TYPE_ELITE_KNIGHT,
                                TROOP_TYPE_KINGSGUARD_KNIGHT,
                                TROOP_TYPE_TRAVELING_KNIGHT,
                                TROOP_TYPE_DEMON_HORROR,
                                TROOP_TYPE_VET_DEMON_HORROR,
                                TROOP_TYPE_MARAUDER,
                                TROOP_TYPE_VET_MARAUDER,
                                TROOP_TYPE_PYROMANIAC,
                                TROOP_TYPE_VET_PYROMANIAC,
                                TROOP_TYPE_RENEGADE_NORSEMAN_WARRIOR,
                                TROOP_TYPE_RENEGADE_SABER_WARRIOR,
                                TROOP_TYPE_RENEGADE_CULTIST_WARRIOR,
                                TROOP_TYPE_RENEGADE_SAI_WARRIOR,
                                TROOP_TYPE_SABER_CLEAVER,
                                TROOP_TYPE_VET_SABER_CLEAVER,
                                TROOP_TYPE_RENEGADE_SWASHBUCKLER,
                                TROOP_TYPE_MUSCLE_MAN,
                                TROOP_TYPE_BONE_HUNTRESS,
                                TROOP_TYPE_MASTER_BONE_HUNTRESS
                                ]


def is_attack_range_troop(troopType):
    return troopType in ALL_ATTACK_RANGE_TROOPS


def is_attack_melee_troop(troopType):
    return troopType in ALL_ATTACK_MELEE_TROOP_TYPES
